[build]
  command = "ng build"
  publish = "dist/flamsoft-frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301